### ISSUE TITLE
Is it possible to run CINDA with unique IDs but NOT in the range from 1 to n?

### ISSUE THREAD

**Issue by iamlvm** [yu-lab-vt/CINDA#10]
Thanks for publishing this offline tracking algorithm.

I think unique IDs in `detection_arcs` are enough to link detections as a trajectory. Do you have any suggestions to implement CINDA with unique IDs but NOT in the increasing order from `1` to `n`?
For example, I can have unique IDs in the following order `1, 200000000000, 3, 9, 5` and know how to put them in `transition_mat`. How can I run CINDA with this input?
```
1,3.467864,4.1917836,-6.7232538
200000000000,4.2795971,2.9235461,-7.1020659
3,1.7165976,2.4109024,-5.2415588
9,3.6710802,2.5107691,-5.7177933
5,3.3307807,3.359227,-6.3914796
```

I have tried to run CINDA with this input. It outputted an error (`Error 5, wrong value of nodes`). I do not know if I ignore (comment) this line (`if ( tail < 0  ||  tail > n  || head < 0  ||  head > n  )`) can possibly affect the output of CINDA.

**Comment by ccwang92** [comment]
Hi,

Sure. One direct way is to map the original ids to ids in the range 1 to n. Then input the graph with new ids to CINDA. After getting the output, we can use the map to retrieve the original ids.
It is not prefered to use the original ids directly because it may wastes memory for those non-exist nodes.

Thanks,
